UrbanKickzz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UrbanShoeApp.urls'))
]

UrbanShoeApp/urls.py
from django.urls import path
from UrbanShoeApp import views
from django.contrib.auth.views import LoginView,LogoutView


urlpatterns = [  
    path('',views.home_view,name=''),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('logout', LogoutView.as_view(template_name='ecom/logout.html'),name='logout'),
    path('aboutus', views.aboutus_view),
    path('contactus', views.contactus_view,name='contactus'),
    path('search', views.search_view,name='search'),
    path('send-feedback', views.send_feedback_view,name='send-feedback'),
    path('view-feedback', views.view_feedback_view,name='view-feedback'),
path('seller-dashboard/', views.seller_dashboard_view, name='seller-dashboard'),
    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(template_name='ecom/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
path('edit-order/<int:product_id>/', views.edit_order, name='edit-order'),

path('seller-edit-order/<int:product_id>/', views.seller_edit_order, name='seller-edit-order'),
    path('view-customer', views.view_customer_view,name='view-customer'),
    path('delete-customer/<int:pk>', views.delete_customer_view,name='delete-customer'),
    path('update-customer/<int:pk>', views.update_customer_view,name='update-customer'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment_failure/', views.payment_failure, name='payment_failure'),
    path('order_detail/', views.order_detail, name='order_detail'),
    path('admin-products', views.admin_products_view,name='admin-products'),
    path('admin-add-product', views.admin_add_product_view,name='admin-add-product'),
    path('delete-product/<int:pk>', views.delete_product_view,name='delete-product'),
    path('update-product/<int:pk>', views.update_product_view,name='update-product'),

    path('admin-view-booking', views.admin_view_booking_view,name='admin-view-booking'),
    path('order-pdf/<int:order_id>/', views.generate_pdf, name='order-pdf'),
    path('order-seller-pdf/<int:order_id>/', views.generate_seller_pdf, name='order-seller-pdf'),
    path('admin_view_selling_view', views.admin_view_selling_view,name='admin_view_selling_view'),
    path('delete-order/<int:pk>', views.delete_order_view,name='delete-order'),
    path('delete-seller-order/<int:pk>', views.delete_seller_order_view,name='delete-seller-order'),
    path('update-order/<int:pk>', views.update_order_view,name='update-order'),
    path('update-seller-order/<int:pk>', views.update_seller_order_view,name='update-seller-order'),
    path('customersignup', views.customer_signup_view,name='customersignup'),
    path('customerlogin', LoginView.as_view(template_name='ecom/customerlogin.html'),name='customerlogin'),
    path('customer-home', views.customer_home_view,name='customer-home'),
    path('customer-pdf/<int:order_id>/', views.generate_order_pdf_view, name='customer-pdf'),
    path('seller-pdf/<int:order_id>/', views.generate_sellerorder_pdf_view, name='seller-pdf'),
    path('my-order', views.my_order_view,name='my-order'),
    # path('my-order', views.my_order_view2,name='my-order'),
    path('my-profile', views.my_profile_view,name='my-profile'),
    path('edit-profile', views.edit_profile_view,name='edit-profile'),
    
    path('download-invoice/<int:orderID>/<int:productID>', views.download_invoice_view,name='download-invoice'),


    path('seller-to-cart/<int:pk>', views.seller_to_cart_view,name='seller_cart'),
    path('cart', views.mycart,name='cart'),
     path('cart-seller', views.seller_cart_view,name='cart-seller'),
    path('remove-from-cart/<int:pk>', views.remove_from_cart_view,name='remove-from-cart'),
    path('remove-from-seller/<int:pk>', views.remove_from_cart_seller,name='remove-from-seller'),
    path('customer-address/<int:pk>', views.customer_address_view,name='customer-address'),
    path('payment-success', views.payment_success_view,name='payment-success'),
     path('seller-success', views.seller_success,name='seller-success'),

path('add-to-cart/<int:id>/', views.addtocart, name='add-to-cart'),

   path('my-cart',views.mycart, name='my-cart'),

   path('managecart/<int:id>/',views.managecart,name="managecart"),

path('seller-add-to-cart/<int:id>/', views.selleraddtocart, name='seller-add-to-cart'),

   path('sellercart',views.sellercart, name='sellercart'),

   path('sellermanagecart/<int:id>/',views.sellermanagecart,name="sellermanagecart"),

path('seller-address/<int:pk>', views.seller_address_view,name='seller-address'),
path('seller-order', views.seller_order_view,name='seller-order'),
path('termsnconditions', views.termsnconditions,name='termsnconditions'),
path('analytics', views.analytics,name='analytics'),


]

UrbanShoeApp/models.py
from django.db import models
from django.db.models import Count, Sum
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    USER_TYPE_CHOICES = [
         ('customer', 'Customer'),
        ('seller', 'Seller'),
    ]
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/CustomerProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='customer')
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return self.user.first_name
    def get_sellercart_total_earning(self):
        return self.sellercart_set.aggregate(total_earning=Sum('sellerorders__cart__cartproduct__subtotal'))['total_earning'] or 0
    

class Product(models.Model):
    name=models.CharField(max_length=40)
    product_image= models.ImageField(upload_to='product_image/',null=True,blank=True)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=20)
    description=models.CharField(max_length=40)
    def __str__(self):
        return self.name
    
    def update_product_quantities(self):
        # Update product quantities based on the items in the cart
        cart_products = CartProduct.objects.filter(cart=self.cart)
        for cart_product in cart_products:
            product = cart_product.product
            product.quantity -= cart_product.quantity
            product.save()





class Feedback(models.Model):
    name=models.CharField(max_length=40)
    feedback=models.CharField(max_length=500)
    date= models.DateField(auto_now_add=True,null=True)
    def __str__(self):
        return self.name



class cart(models.Model):
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)



class CartProduct(models.Model):
    cart = models.ForeignKey(cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "cart:" + str(self.cart.id) + "cartproduct:" + str(self.id)
    

class Orders(models.Model):
    STATUS =(
        ('Pending','Pending'),
        ('Order Confirmed','Order Confirmed'),
        ('Out for Delivery','Out for Delivery'),
        ('Delivered','Delivered'),
    )
    customer=models.ForeignKey('Customer', on_delete=models.CASCADE,null=True)
   
    email = models.CharField(max_length=50,null=True)
    address = models.CharField(max_length=500,null=True)
    mobile = models.CharField(max_length=20,null=True)
    order_date= models.DateField(auto_now_add=True,null=True)
    status=models.CharField(max_length=50,null=True,choices=STATUS)
    cart=models.ForeignKey(cart,on_delete=models.CASCADE,null=True)
    
    def update_product_quantities(self):
        # Update product quantities only when the order status changes to 'Order Confirmed'
        if self.status == 'Out for Delivery':
            cart_products = CartProduct.objects.filter(cart=self.cart)
            for cart_product in cart_products:
                product = cart_product.product
                product.quantity -= cart_product.quantity
                product.save()

            # Set the order status to 'Order Confirmed' after updating product quantities
            self.save()
#Sellerss.................


class sellercart(models.Model):
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='sellercarts')
    total = models.PositiveIntegerField(default=0)

class Order(models.Model):
    order_id = models.CharField(max_length=100, unique=True)
    total_amount = models.PositiveIntegerField()
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    products = models.ManyToManyField('Product', through='OrderProduct')

    def __str__(self):
        return self.order_id

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return f"Order: {self.order.order_id}, Product: {self.product.name}"

class SellerCartProduct(models.Model):
    cart = models.ForeignKey(sellercart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField(default=0)
    grade = models.CharField(max_length=500,null=True)

    def __str__(self):
        return "cart:" + str(self.cart.id) + "cartproduct:" + str(self.id)
    

class SellerOrders(models.Model):
    STATUS =(
        ('Pending','Pending'),
        ('Order Confirmed','Order Confirmed'),
        ('Out for Pickup','Out for Pickup'),
        ('Stored in Warehouse','Stored in Warehouse'),
        
    )
    seller=models.ForeignKey('Customer', on_delete=models.CASCADE,null=True)
    email = models.CharField(max_length=50,null=True)
    address = models.CharField(max_length=500,null=True)
    mobile = models.CharField(max_length=20,null=True)
    order_date= models.DateField(auto_now_add=True,null=True)
    status=models.CharField(max_length=50,null=True,choices=STATUS)
    cart=models.ForeignKey(sellercart,on_delete=models.CASCADE,null=True)

UrbanShoeApp/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models
from django.contrib.auth.forms import UserCreationForm


class CustomerUserForm(forms.ModelForm):
    USER_TYPE_CHOICES = [
        ('customer', 'Customer'),
        ('seller', 'Seller'),
    ]

    user_type = forms.ChoiceField(choices=USER_TYPE_CHOICES, required=True)
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'user_type']
        widgets = {
            'password': forms.PasswordInput(),
            
        }

class CustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = ['address', 'mobile','user_type']  


class ProductForm(forms.ModelForm):
    class Meta:
        model=models.Product
        fields=['name','price','quantity','description','product_image']

#address of shipment
class AddressForm(forms.Form):
    Email = forms.EmailField()
    Mobile= forms.IntegerField()
    Address = forms.CharField(max_length=500)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model=models.Feedback
        fields=['name','feedback']

#for updating status of order
class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Orders
        fields = ['address', 'mobile', 'status']

    # Additional fields from CartProduct
    product = forms.ModelChoiceField(queryset=models.CartProduct.objects.all().values_list('product', flat=True).distinct(), required=False)
    rate = forms.IntegerField(required=False)
    quantity = forms.IntegerField(required=False)
    subtotal = forms.IntegerField(required=False)

    # Additional field from Cart
    total = forms.IntegerField(required=False)

class EditOrderForm(forms.ModelForm):
    class Meta:
        model = models.CartProduct
        fields = ['product','rate','quantity', 'subtotal']        
    
    def __init__(self, *args, **kwargs):
        super(EditOrderForm, self).__init__(*args, **kwargs)

        # Make 'product' and 'rate' fields read-only
        self.fields['product'].widget.attrs['readonly'] = True
        self.fields['rate'].widget.attrs['readonly'] = True

        # Disable the 'product' and 'rate' fields from being rendered as HTML input elements
        self.fields['product'].disabled = True
        self.fields['rate'].disabled = True

class SellerOrderForm(forms.ModelForm):
    class Meta:
        model = models.SellerOrders
        fields = ['address', 'mobile', 'status']

    # Additional fields from CartProduct
    product = forms.ModelChoiceField(queryset=models.SellerCartProduct.objects.all().values_list('product', flat=True).distinct(), required=False)
    rate = forms.IntegerField(required=False)
    quantity = forms.IntegerField(required=False)
    subtotal = forms.IntegerField(required=False)

    # Additional field from Cart
    total = forms.IntegerField(required=False)

class SellerEditOrderForm(forms.ModelForm):
   

    class Meta:
        model = models.CartProduct
        fields = ['product', 'rate', 'quantity', 'subtotal']

    def __init__(self, *args, **kwargs):
        super(SellerEditOrderForm, self).__init__(*args, **kwargs)

        # Make 'product' and 'rate' fields read-only
        self.fields['product'].widget.attrs['readonly'] = True
        self.fields['rate'].widget.attrs['readonly'] = True

        # Disable the 'product' and 'rate' fields from being rendered as HTML input elements
        self.fields['product'].disabled = True
        self.fields['rate'].disabled = True

#for contact us page
class ContactusForm(forms.Form):
    Name = forms.CharField(max_length=30)
    Email = forms.EmailField()
    Message = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'rows': 5, 'cols': 30}))


class SellerAddressForm(forms.Form):
    Mobile= forms.IntegerField()
    PickupAddress = forms.CharField(max_length=500)

UrbanShoeApp/templates/ecom/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Urban-Kickzz</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <style>
        body {
            background-color: #ffffff;
            color: #ffffff;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            overflow-x: hidden;
            font-family: 'Arial', sans-serif;
        }

        #navbar {
            background-color: #000000;
            color: #ffffff;
            padding: 10px;
        }

        .navbar-nav {
            display: flex;
            align-items: center;
        }

        .navbar-brand,
        .nav-item,
        .nav-link.active {
            color: #ffffff !important;
            font-size: 20px;
            font-weight: 500;
            margin-right: 20px;
            text-decoration: none;
        }

        .cart-button {
            text-decoration: none;
            display: inline-block;
            padding: 10px 20px;
            background-color: #FFFFFF;
            color: black;
            border-radius: 5px;
            margin-right: 10px;
        }

        .cart-button i {
            margin-right: 5px;
            vertical-align: middle;
        }

        .cart-button:hover {
            background-color: #FFCC33;
            color: #ffffff;
        }
        .cart-button:hover .cart-icon {
            fill: #ffffff;
        }

        .container {
            margin-top: 30px;
        }

        .panel {
            border: 1px solid #ddd;
            border-radius: 8px;
            overflow: auto;
            background-color: #ffffff;
            color: #000000;
        }

        .panel-heading {
            background-color: #000000;
            color: #ffffff;
            text-align: center;
            font-size: 18px;
            padding: 10px;
        }

        .table {
            margin-bottom: 0;
            color: #000000;
        }

        .table th,
        .table td {
            border: 1px solid #ddd;
            text-align: center;
            font-size: 14px;
            padding: 8px;
        }

        .btn-primary,
        .btn-danger,
        .btn-success {
            font-size: 14px;
            padding: 10px 25px;
        }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

        .btn-danger:hover {
            background-color: #bd2130;
            border-color: #bd2130;
        }

        .btn-success:hover {
            background-color: #218838;
            border-color: #218838;
        }

        .btn-lg {
            font-size: 18px;
            padding: 20px 30px;
        }

        td {
            text-align: center;
        }

        .btn {
            margin: 0 5px;
            padding: 5px 10px;
            font-size: 14px;
        }

        .quantity {
            font-weight: bold;
            margin: 0 5px;
            font-size: 14px;
        }

        .total-price {
            font-size: 14px;
        }

        footer {
            background-color: #000000;
            color: #ffffff;
            padding: 20px 0;
            text-align: center;
            position: relative;
        }

        .footer-icon {
            font-size: 18px;
            margin-right: 5px;
        }

        @media screen and (max-width: 576px) {
            .navbar-nav {
                flex-direction: column;
                align-items: flex-end;
            }

            .navbar-nav .nav-item {
                margin-bottom: 5px;
                text-align: right;
            }
        }

        .navbar-toggler-icon {
            background-color: #ffffff;
            border-radius: 4px;
            padding: 2px;
            transition: border 0.3s ease;
        }

        .navbar-toggler:hover .navbar-toggler-icon {
            border: 2px solid #ffffff;
        }

        body {
            margin: 0;
            padding: 0;
        }

        #element-above-first-navbar {
            margin-bottom: 0;
        }

        #element-below-second-navbar {
            margin-top: 0;
        }

        @media screen and (min-width: 577px) {
            .navbar-nav {
                margin-left: auto;
            }
        }
    </style>
</head>

  <!--First navbar-->
<nav class="navbar navbar-expand-sm bg-body-dark" id="navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/Shoe Logo2.png' %}" alt="Urban-Kickzz Logo" height="60" width="200" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/my-order">Dashboard</a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="nav-link active" aria-current="page">Logout</button>
                    </form>
                </li>
            </ul>
            <a class="cart-button" href="/">
                <svg class="cart-icon" width="24" height="24" viewBox="0 0 24 24">
                <!-- Add your cart icon SVG path here -->
                    <path d="M15.32 2.405H4.887C3 2.405 2.46.805 2.46.805L2.257.21C2.208.085 2.083 0 1.946 0H.336C.1 0-.064.24.024.46l.644 1.945L3.11 9.767c.047.137.175.23.32.23h8.418l-.493 1.958H3.768l.002.003c-.017 0-.033-.003-.05-.003-1.06 0-1.92.86-1.92 1.92s.86 1.92 1.92 1.92c.99 0 1.805-.75 1.91-1.712l5.55.076c.12.922.91 1.636 1.867 1.636 1.04 0 1.885-.844 1.885-1.885 0-.866-.584-1.593-1.38-1.814l2.423-8.832c.12-.433-.206-.86-.655-.86 " fill="#000000"/>
                </svg>
                Add More Products
            </a>
        </div>
    </div>
</nav>
<hr><br><br><br>
  <div class="container">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h6 class="panel-title">My Cart</h6>
      </div>
    <div class="table-responsive">
      <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Description</th>
          <th>Total Price</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for p in cart.cartproduct_set.all %}
          {% if p %}
            <tr>
              <td>{{ p.product.name }}</td>
              <td>Rs. {{ p.product.price }} </td>
              <td>
                <a href="managecart/{{p.id}}?action=dcr" class="btn btn-success">-</a>
                <span class="quantity">{{ p.quantity }}</span>
                <a href="managecart/{{p.id}}?action=inc" class="btn btn-success">+</a>
              </td>
              <td>{{ p.product.description }}</td>
              <td class="total-price">Rs. {{ p.subtotal }}</td>
              <td><a class="btn btn-danger btn-xs" href="managecart/{{p.id}}?action=rmv"><span class="glyphicon glyphicon-trash">delete</span></a></td>
            </tr>
          {% else %}
            <br><br><br>
            <h1>No products</h1>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  </div>
</div>
<br><br><br>
<div style="text-align: center;">
  {% if cart.cartproduct_set.exists %}
    <button class="btn btn-danger btn-lg btn-total">Total Rs.{{ cart.total }}</button>
    <a href="/customer-address/{{cart.id}}"><button class="btn btn-success btn-lg"><span>Purchase </span></button></a>
  {% else %}
    <p style="text-decoration: none; color: #000000;">No products in the cart.</p>
    <p><a href="/" class="btn btn-dark btn-lg d-block mx-auto" style="text-decoration: none; color: #fff; padding: 12px 24px; width: 200px;">
        Go back to Home
    </a>
</p>

  {% endif %}
</div>


<br><br><br><br><br><br><br><br>
<footer style="padding: 10px 0;">
  <center style="list-style-type: none; padding: 0; margin: 0; font-size: 14px;">
      <!-- Example links in the navigation menu with Material Icons and reduced size -->
      <li class="upper-links" style="list-style-type: none; padding: 0; margin: 0;">
          <a href="#" style="color: #FFFFFF; text-decoration: none;">
              <i class="material-icons footer-icon" style="font-size: 16px;">description</i> <!-- Icon for Terms and Conditions -->
              Terms and Conditions |  <i class="material-icons footer-icon" style="font-size: 16px;">privacy_tip</i> <!-- Icon for Privacy Policy --> Privacy Policy
          </a>
      </li>
  </center>
  <center style="font-size: 14px;">
      <div style="color:#ffffff; font-size: 16px;" class="wow fadeInUp footer-copyright">
        <p>Urban-Kickzz &copy; 2024 | UrbanShoes | All rights received</p>
    </div>
  </center>
</footer>
</body>
</html>

<script>
  $(document).ready(function () {
    // Function to handle quantity increase
    $(".quantity-increase").on("click", function () {
      updateQuantity($(this), 10);
    });

    // Function to handle quantity decrease
    $(".quantity-decrease").on("click", function () {
      updateQuantity($(this), -10);
    });

    // Function to update quantity
    function updateQuantity(button, change) {
      var inputField = button.closest("tr").find(".quantity-input");
      var currentQuantity = parseInt(inputField.val());
      var maxQuantity = parseInt(inputField.data("max-quantity"));
      var pricePerKg = parseFloat(inputField.data("price-per-kg"));

      if (currentQuantity + change >= 20 && currentQuantity + change <= maxQuantity) {
        currentQuantity += change;

        // Update input field value
        inputField.val(currentQuantity);

        // Update total price
        updateTotalPrice(inputField, pricePerKg, currentQuantity);

        // Update total
        updateTotal();
      }
    }

    // Function to update total price
    function updateTotalPrice(inputField, pricePerKg, quantity) {
      var totalElement = inputField.closest("tr").find(".total-price");
      var total = pricePerKg * quantity;
      totalElement.text("Rs. " + total.toFixed(2));
    }

    // Function to update total
    function updateTotal() {
      var total = 0;
      $(".total-price").each(function () {
        total += parseFloat($(this).text().replace("Rs. ", ""));
      });

      // Update total button
      $(".btn-total").text("Total Rs." + total.toFixed(2));
    }
  });
</script>

UrbanShoeApp/templates/ecom/edit_order.html
{% extends 'ecom/admin_base.html' %}
{% load widget_tweaks %}
{% block content %}

<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<br><br>

<form method="post">
  {% csrf_token %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow"> <!-- Added 'shadow' class for card shadow effect -->
          <div class="card-body">
            <h5 class="card-title text-center">Update Order Status</h5><br>
            <form method="post" action="{% url 'edit-order' product.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center mt-3">
                  <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

{% endblock content %}

UrbanShoeApp/templates/ecom/feedback_sent.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}



  {%if request.user.is_authenticated%}
    {% include "ecom/customer_navbar.html" %}
  {%else%}
    {% include "ecom/navbar.html" %}
  {%endif%}
<br><br><br>
<h3 style="color:blue;text-align:center;">Your Feedback Sent Succesfully !</h3>
<br>
<div style="text-align:center;">
  <img src="{% static "images/success.png" %}"  style="width:100px; height:100px; ">
</div>

<br><br><br><br><br><br><br><br>
  {% include "ecom/footer.html" %}